language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  local_dir: dist/
  skip_cleanup: true
  api_key:
    secure: XpTqIcjiHNnvASx14Ohh5l57HWcVtPJ7CBLVBsUcmhz2mnHULy548ZwSFHxcs3I+XrbRi1F0n7Ugy33BXm1GQ/d+kEKZCZy/SbBR3d9jnQXo4uwmE84wXeTbxkmkW6tEuH2YnT+5GpbBlnddBQL020rylquP8KHU9Ja8dI83pgkxwLEHRzBL7tN6xjC7yAnRyvaauWew5c3rHqSDib6KR/eRJYYcaW10oFI2hXPMODxHqyT9JQpSihlbR4Tt4wV7OCVqDvLDChgGwu+4s7FWpO4saQdvMQKnqOacAEDeL7Zoivgk+Yb1jTL6CSIHjjJV/4BZCbGi4NA2FvF3l8vvbrU6ta1dayzJFFxg58uHSehFTx9zC0HunFp/jqfoF3QRumPpGpOtESZJt2prLhoiOPDPbJtyjuUnzPtmUAeHH9JBf3kHhMNby1ZElpURJtAsMrtpbbsbF7coJ/dEjOfBnEBJiUvpe+LAicEMgwbNusNllXXOSnQxfeIgVGTu6jERwRZgTjS75j+N/0/NBolk2HlZqq8YMiJV7ZwBJbbpgPTvM6o8R8i0yhSels7jFpyVUac90RVVv+uIYPr7RPDnRHx7YbVXk5zHUh9W3Pz0BgZoSm2Jg/FhfUrwojDNMyUNeVCk0gAJbRjat/Hf9Er5CT0mwWZaT4uj8/eNhV0Zd0o=
  app: synconlive
  on:
    repo: nmelihsensoy/syncOn.live
