language: node_js
node_js: node
cache:
  directories:
  - node_modules
  - Front-End/node_modules
before_install:
- npm install
- cd ./Front-End
- npm install
- rm package.json
- yarn install
script:
- yarn run build
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: jDD3+sJpzX9xCIgTo/0EzgLu+0sskjsFXv0O48QtxMgR8l+j3zMIu8FCPA2Fdp63i0eySBz5VwEJm9VnJuQM7NPVOVB49L7gL9qEYmYtyNEt3bfHw9drpZgpcoFTQgsf0UBuewDO2HvYydiK9mMHwKRXM+hDMEpd8ER9wDNWnK09P38ZoBNLMC/qzanGO/ruyEWz3XJsuufqJn+Iz19I7Epu/viI1dIO+as1vU/CPgnelIWFRpHSB8A4BsBxE4vQqGXWUTJfqQKAadbOXi+hUVpqqX60meOxq9AoGybns4n34yugxuDS5JZqjYxvnxq4UCPOWrBgpK/JnKdjxMIWbSF1aR8XfXhxyyDAc4JhfP0eJqIOOhIXZG14AAOe9O5OsTcWR84WzHGJkIKCIutE5wj5PudEYE7mkLdwLvBWl606N4EebscVkXAH+oI1ayruYuIOewoZBFiSl9jP33/Pl7gWfVBNsNXr6CvpqCyLH7g98UtB5MRHScA1RI9bOymSNjTZK6IAqzi+B64XcI7cFZukD4O6kZDTjRYkU65vgkFYxXLshl2H9gjLfeXPdbqXo0ZKDPP5JKfAg0IEW9VlbD3TykCFjQZHkgAsE3ot9MQUDHHR9tNWAQ484jRYuebQi2/flmltfC9OmYVJjQnpjubjKznrU7U9bzC5J5JuaWU=
  app: synconlive
  on:
    repo: nmelihsensoy/syncOn.live
