language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  local_dir: dist/
  skip_cleanup: true
  api_key:
    secure: jXYzmIxxtd2ny2mruAVaA1JOrJQbVCLgw+DjG+/LITa5OZKx0Uzt2MBzGxSihUfBPvLqrzj0xcouJcqhQFPLGpv8U4i2Jn/IfmKYddQDhBsVptFd/dhrFDshucyOFzT+D5nqJBt3aA6ljU7hwD1fgfdUSUrw9/YBESudVRYijvTyyFW9raMvPli7BBnifnn5GECwV5PrDx4Ppbplu+QSgYVvwVe1K0ARi/1/EIJB5xQ7LdRcmjKGGLJx1nLB4CojtDdQlQz4jYKXbKHPhVqC0GBtbjkPa7UH5MqZBSOuvbjwUhds9qr6fqXtJSWGM983ZwCfWwJ/VGX9obCWv45/Bg5gyftXfsmZQKqHxP9AmkynHdJPc0Q6SGvV/9uH0lY4sl9Q9nJb+OeJ6w5eWMqaa/crxVOr1GG+lwyYK4bn0CajWde8pb4P5+8SJwARp82oJKy17Ra83j3byaOm8omAUcvuUxGkaxfuPiXId7vyDefSbi+mxU+opMUTvHby1Y3aFv10OyiJWiILqqWcpBu6DAbRVQV0j6UkPRKrB4lmmvinY+8qC64DA8IDe5UHwydlg8hfa2l3INlg/LMADvnXoG8J5XM7Uh1VNQzCNP+/HXYJMcmkUi3m21LmKZyLcPgO19zF2lZIM4zdetIn6GUDRpAhNNs786/E2Oi4c+IlMkE=
  app: synconlive
  on:
    repo: nmelihsensoy/syncOn.live
